[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/rest/*"
  to = "/.netlify/functions/jira-proxy?path=/rest/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[functions]
  directory = "netlify/functions"
